version: '3'

services:
  #* NATS SERVER (MESSAGING SYSTEM)
  nats-server:
    container_name: nats-server
    image: nats:latest

  #* CLIENT GATEWAY
  client-gateway:
    container_name: client-gateway
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

  #* AUTH MICROSERVICE
  auth-ms:
    container_name: auth-ms
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: auth-ms-prod
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  #* PRODUCTS MICROSERVICE
  products-ms:
    container_name: products-ms
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: products-ms-prod
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  # #* ORDERS MICROSERVICE
  # orders-ms:
  #   container_name: orders-ms
  #   build:
  #     context: ./orders-ms
  #     dockerfile: dockerfile.prod
  #   image: orders-ms-prod
  #   environment:
  #     - PORT=3002
  #     - NATS_SERVERS=nats://nats-server:4222
  #     - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/ordersdb?schema=public

  #* PAYMENTS MICROSERVICE
  payments-ms:
    container_name: payments-ms
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: payments-ms-prod
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - NATS_SERVERS=nats://nats-server:4222
